config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :github_finder, only: :index do
    collection do
      post :check_repo
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/github_finder_controller.rb
class GithubFinderController < ApplicationController

  def check_repo
    query_param = params.dig('github_finder', 'search') || ''
    @data = ::DataFetcher::GetRepositoryDetails.new(query_param).fetch
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/github_finder/_form.html.erb
<div class='text-center'>
  <h3>Welcome to GitHub Repository Searcher</h3>
</div>
<div class=>
  <%= form_for :github_finder, url: check_repo_github_finder_index_url do |f| %>
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <%= f.text_field :search, class: 'form-control' %> <br>

      <%= f.submit :SEARCH,
                    class: 'btn btn-sm fw-bold form-control',
                    style:"width: 100%; background-color: #0366d6; color: #fff;"  %>
    </div>
  <% end %>
</div>

app/views/github_finder/check_repo.html.erb
<div>
  <%= render partial: 'form' %>
</div>

<div>
  <% if @data['items'].present? %>
    <table class="table">
      <th>
        <div class='text-center'>
          <span class="bold">Total Count:</span> <%= @data['total_count'] %>
          <span class="bold">Incomplete Results:</span> <%= @data['incomplete_results'] %>
        </div>
      </th>
      <% @data['items'].each do |item| %>
        <tr>
          <table class="table">
            <% item.each_with_index do |(key, value), index| %>
              <tr>
                <td><span><%= key %>: <%= value %></span></td>
              </tr>
            <% end %>
          </table>
        </tr>
      <% end %>
    </table>
  <% else %>
    <div class='text-bottom' style='vertical-align: text-bottom'>
      <span class="bold"> No results Found </span>
    </div>
  <% end %>
</div>

app/views/github_finder/index.html.erb
<%= render partial: 'form' %>

app/views/homepage/_form.html.erb
<div class='text-center'>
  <h3>Welcome to GitHub Repository Searcher</h3>
</div>
<div class=>
  <%= form_for :homepage, url: check_repo_homepage_index_url do |f| %>
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <%= f.text_field :search, class: 'form-control' %> <br>

      <%= f.submit :SEARCH,
                    class: 'btn btn-sm fw-bold form-control',
                    style:"width: 100%; background-color: #0366d6; color: #fff;"  %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GithubRepoFinder</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true%>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>